# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Haruno Kenobi
email: haruno.kenobi@gmail.com
description:  Olá, sou Haruno Kenobi e estou criando o meu primeiro blog. 
              Sou desenvolvedor .net/c# e logo logo estarei trazendo coisas bem bacanas!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: HarunoKenobi
github_username:  HarunoKenobi

# Build settings
markdown: kramdown
